variable "owner" {}
variable "aws_region" {}
variable "project_name" {}
variable "rds_address" {}
variable "rds_db_name" {}
variable "rds_port" {}
variable "rds_user" {}
variable "rds_password" {}
variable "s3_bucket_name" {}
variable "iam_user_access_id" {}
variable "iam_user_access_secret" {}
variable "tags" {}
