variable "owner" {}
variable "aws_region" {}
variable "project_name" {}
variable "domain_name" {}
variable "vpc_id" {}
variable "public_subnets" {}
variable "ec2_id" {}
variable "sg_alb" {}
variable "tags" {}
